Vagrant.configure("2") do |config|
  config.vm.box = "tumbleweed_latest"
  config.vm.hostname = "tumbleweedLatest"
  config.vm.box_url = "https://build.opensuse.org/package/binaries/Virtualization:Appliances:Images:openSUSE-Tumbleweed/openSUSE-Tumbleweed-Vagrant:virtualbox/openSUSE_Tumbleweed"
  config.vm.synced_folder "shared/", "/app"
  config.vm.network "forwarded_port", guest: 3000, host: 3000
  config.vm.network "forwarded_port", guest: 6443, host: 6443
  config.vm.provision "shell", path: "provision.sh"
end
